Fix incorrect definition of SOFTPWM_DEFINE_PIN63_CHANNEL
Incorrect register name "DDRK1" caused compilation to fail when SOFTPWM_DEFINE_PIN63_CHANNEL or SOFTPWM_DEFINE_PINA9_CHANNEL macros were used:

error: 'DDRK1' was not declared in this scope